Script started on 2015年06月21日 (週日) 12時17分10秒
]0;F74036271@2015cpp: ~/lab7F74036271@2015cpp:~/lab7$ ./lab7
for loop: new mino_ptr[0]
for loop: new mino_ptr[1]
for loop: new mino_ptr[2]
new_hand():delete mino_ptr[0, 1]
for loop: new mino_ptr[3]
for loop: new mino_ptr[4]
new_hand():delete mino_ptr[2, 3]
for loop: new mino_ptr[5]
for loop: new mino_ptr[6]
new_hand():delete mino_ptr[4, 5]
for loop: new mino_ptr[7]
for loop: new mino_ptr[8]
new_hand():delete mino_ptr[6, 7]
for loop: new mino_ptr[9]
]0;F74036271@2015cpp: ~/lab7F74036271@2015cpp:~/lab7$ [K]0;F74036271@2015cpp: ~/lab7F74036271@2015cpp:~/lab7$ exit

Script done on 2015年06月21日 (週日) 12時17分59秒
